apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-fase-4-products-deployment
  labels:
    app: tech-challenge-fase-4-products-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-fase-4-products-deployment
  template:
    metadata:
      labels:
        app: tech-challenge-fase-4-products-deployment
    spec:
      containers:
      - name: tech-challenge-fase-4-products-app
        image: raffiuds/tech-challenge-fase-4-products:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: tech-challenge-fase-4-products-api-config
              key: POSTGRES_DB
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: tech-challenge-fase-4-products-api-config
              key: DB_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tech-challenge-fase-4-products-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tech-challenge-fase-4-products-secrets
              key: POSTGRES_PASSWORD
        livenessProbe:
          httpGet:
            path: /api/v1
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 15
        resources:
          requests:
            cpu: 500m

