name: "Deploy"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Migrate
        env:
          DB_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}
        run: make migrate

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: raffiuds/tech-challenge-go-app:latest
          context: .

      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region us-east-1
  
      - name: Kube Apply
        run: |
          kubectl apply -f k8s/
